# Task-5

In [1]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [2]:
df = pd.read_csv("bank-full.csv",sep=";")
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [3]:
X = df.drop('y', axis=1)
y = df['y']

In [4]:
y = y.map({'no': 0, 'yes': 1})

In [5]:
numeric_columns = [
    'age',
    'balance',
    'day',
    'duration',
    'campaign',
    'pdays',
    'previous'
]

print("Numerical columns:")
print(numeric_columns)

Numerical columns:
['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [6]:
categorical_columns = X.select_dtypes(
    include=['object']
).columns.tolist()

print("\nCategorical columns:")
print(categorical_columns)

Categorical columns:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

In [7]:
X = pd.get_dummies(X, columns=categorical_columns, drop_first=True)

In [8]:
X = X.astype(int)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [10]:
scaler = StandardScaler()

X_train[numeric_columns] = scaler.fit_transform(
    X_train[numeric_columns]
)

X_test[numeric_columns] = scaler.transform(
    X_test[numeric_columns]
)

In [11]:
X_train

,age,balance,day,duration,campaign,pdays,previous,job_blue-collar,job_entrepreneur,job_housemaid,...,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_other,poutcome_success,poutcome_unknown
24001,-0.460434,-0.164410,1.582124,-0.457311,-0.246104,-0.410910,-0.241509,0,0,0,...,0,0,0,0,0,0,0,0,0,1
43409,-1.589641,0.899627,-1.298384,2.502493,0.398202,1.446096,2.664584,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20669,0.292371,-0.365486,-0.458236,5.697691,0.398202,-0.410910,-0.241509,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18810,0.668773,-0.445003,1.822166,-0.862499,2.653271,-0.410910,-0.241509,0,0,0,...,1,0,0,0,0,0,0,0,0,1
23130,-0.272233,-0.361249,1.222060,-0.777602,2.331118,-0.410910,-0.241509,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17958,0.856974,-0.146160,1.702145,-0.773743,-0.246104,-0.410910,-0.241509,1,0,0,...,1,0,0,0,0,0,0,0,0,1
15941,-0.460434,-0.437834,0.741975,-0.700423,0.720354,-0.410910,-0.241509,0,0,0,...,1,0,0,0,0,0,0,0,0,1
16952,0.386471,-0.419258,1.102039,-0.619386,-0.568256,-0.410910,-0.241509,1,0,0,...,1,0,0,0,0,0,0,0,0,1
34781,-1.307339,0.388954,-1.178363,-0.121583,-0.568256,-0.410910,-0.241509,0,0,0,...,0,0,0,1,0,0,0,0,0,1
44229,1.797980,-0.289227,0.381912,-0.329966,-0.246104,2.704068,3.079741,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [12]:
model = joblib.load("model.pkl")

print("Existing model loaded successfully!")
print(model)

FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

In [ ]:
y_pred = model.predict(X_test)

print("\nFirst 20 predictions:")
print(y_pred[:20])

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Model Evaluation")
print("----------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

In [ ]:
print("Classification Report")
print("---------------------")

print(classification_report(
    y_test,
    y_pred,
    target_names=["No", "Yes"]
))

In [ ]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

In [ ]:
train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

print("Overfitting / Underfitting Check")
print("--------------------------------")
print("Training Accuracy:", train_score)
print("Testing Accuracy :", test_score)

difference = train_score - test_score

print("Difference       :", difference)

In [ ]:
if train_score > 0.90 and difference > 0.10:
    print("Result: Model may be overfitting.")

elif train_score < 0.70 and test_score < 0.70:
    print("Result: Model may be underfitting.")

else:
    print("Result: Model appears to be fitting reasonably well.")